# Generated by Django 5.2 on 2026-09-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='شماره همراه')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('manager', 'مدیر'), ('seller', 'فروشنده'), ('customer', 'مشتری')], default='customer', max_length=50, verbose_name='نقش')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='نگاره شخصی')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='آخرین ورود')),
                ('is_staff', models.BooleanField(default=False, help_text='مشخص می\u200cکند که آیا کاربر می\u200cتواند به این سایت مدیریتی وارد شود یا خیر.', verbose_name='وضعیت کارکنان')),
                ('is_active', models.BooleanField(default=True, help_text='مشخص می\u200cکند که آیا این کاربر باید به عنوان کاربر فعال در نظر گرفته شود یا خیر.به\u200cجای حذف حساب\u200cها، تیک این گزینه را بردارید.', verbose_name='این کاربر فعال است')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر\u200cها',
            },
        ),
    ]
