# Generated by Django 5.2 on 2026-09-30 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='نام اندازه')),
            ],
            options={
                'verbose_name': 'اندازه',
                'verbose_name_plural': 'اندازه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('shipping_province', models.CharField(max_length=128, verbose_name='استان ارسال')),
                ('shipping_city', models.CharField(max_length=128, verbose_name='شهر ارسال')),
                ('shipping_address', models.TextField(verbose_name='آدرس ارسال')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='کد پستی ارسال')),
                ('subtotal', models.PositiveBigIntegerField(default=0, verbose_name='جمع قیمت کالاها')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('shipping_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ نهایی سفارش')),
                ('discount_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('returned', 'برگشت داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='address.address', verbose_name='آدرس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('description', models.TextField(verbose_name='توضیحات کامل درباره کالا')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('category', models.ManyToManyField(related_name='products', to='product.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام تخفیف')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.PositiveBigIntegerField(verbose_name='مقدار تخفیف')),
                ('start_at', models.DateTimeField(verbose_name='شروع تخفیف')),
                ('end_at', models.DateTimeField(verbose_name='پایان تخفیف')),
                ('min_order_amount', models.PositiveBigIntegerField(default=0, verbose_name='حداقل مبلغ سفارش')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='product.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='product.product', verbose_name='کالاها')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نام ویژگی')),
                ('value', models.CharField(max_length=512, verbose_name='مقدار ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'ویژگی کالا',
                'verbose_name_plural': 'ویژگی\u200cهای کالا',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='کد کالا')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='product.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='کالا')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='product.size', verbose_name='اندازه')),
            ],
            options={
                'verbose_name': 'تنوع کالا',
                'verbose_name_plural': 'تنوع کالاها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=512, verbose_name='نام کالا')),
                ('variant_description', models.CharField(blank=True, max_length=512, verbose_name='مشخصات تنوع')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت واحد (تومان)')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product', verbose_name='کالا')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.productvariant', verbose_name='تنوع کالا')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
                'ordering': ('-order__created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='نگاره کالا')),
                ('is_default', models.BooleanField(default=False, verbose_name='نگاره پیش\u200cفرض')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'نگاره کالا',
                'verbose_name_plural': 'نگاره\u200cهای کالا',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='unique_default_image_per_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_variant'),
        ),
    ]
